name: Delivery and Deploy to Production

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: delivery
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -apruz
          remote_path: ${{ vars.HACK_FOLDER }}
          remote_host: ${{ secrets.HACK_HOST }}
          remote_user: ${{ vars.HACK_USER }}
          remote_key: ${{ secrets.HACK_SSH_KEY }}
            
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HACK_HOST }}
          username: ${{ vars.HACK_USER }}
          key: ${{ secrets.HACK_SSH_KEY }}
          script: |
            cd ${{ vars.HACK_FOLDER }}
            docker compose up restapi -d --build